#!/usr/bin/env python3

import sys
import os
import pymongo

def getModules():
    if 'HIVE_DB_URI' in os.environ:
        uri = os.environ['HIVE_DB_URI']
    c = pymongo.MongoClient(uri)
    db_name = uri.split('/')[-1].strip()
    proj = {"$project" : {"_id" : 1.0, "description" : "$description", "name" : "$name", "hardware": "$hardware"}}
    return c[db_name].get_collection("hiveavailablemodules").aggregate([proj])

def getActiveJobs(module):
    if 'HIVE_DB_URI' in os.environ:
        uri = os.environ['HIVE_DB_URI']
    c = pymongo.MongoClient(uri)
    db_name = uri.split('/')[-1].strip()
    if module == "hive_multireg":
        return c[db_name].get_collection("hivejobs").find({"state": "active",
                                                           "pipeline_name":"waggle_multireg",
                                                           "current_module_name":"hive.georegistration"}).count()
    if module == "hive_georegistration":
        return c[db_name].get_collection("hivejobs").find({"state": "active",
                                                           "pipeline_name":"waggle",
                                                           "current_module_name": module.replace("hive_", "hive.")}).count()
    return c[db_name].get_collection("hivejobs").find({"state":"active",
                                                       "current_module_name":module.replace("hive_", "hive.")}).count()

def doData():
    jj = {}
    for j in getModules():
        jj[j["_id"]] = getActiveJobs(j["_id"])
    for jkey, jval in list(jj.items()):
        print(( jkey + ".value " + str(jval) ))
    print(("hive_multireg" + ".value " + str(getActiveJobs("hive_multireg"))))

def doConfig():
    print("graph_title Hive active jobs")
    print("graph_args --base 1000 -l 0")
    print("graph_vlabel Number")
    print("graph_category mongodb")
    print("graph_total total")

    for k in getModules():
        kname = k["_id"]
        print((kname + ".label " + k["name"]))
        print((kname + ".info " + k["description"]))
        print(kname + ".type GAUGE")
        print(kname + ".min 0")
        print(kname + ".draw AREASTACK")

    kname = "Multi Registration"
    kval = "hive_multireg"
    print((kval + ".label " + kname))
    print((kval + ".info " + kname))
    print(kval + ".type GAUGE")
    print(kval + ".min 0")
    print(kval + ".draw AREASTACK")


if __name__ == "__main__":
    from os import environ
    if 'HIVE_DB_URI' in environ:
        uri = environ['HIVE_DB_URI']

    if len(sys.argv) > 1 and sys.argv[1] == "config":
        doConfig()
    else:
        doData()
