#!/usr/bin/env python

import sys
import os
import pymongo

def getPendingPriority(priority):
    if 'HIVE_DB_URI' in os.environ:
        uri = os.environ['HIVE_DB_URI']
    c = pymongo.MongoClient(uri)
    db_name = uri.split('/')[-1].strip()
    return c[db_name].get_collection("hivejobs").find({"state":"pending", "priority":priority}).count()

def doData():
    print( "low-pri" + ".value " + str(getPendingPriority(100)) )
    print( "med-pri" + ".value " + str(getPendingPriority(101)) )
    print( "hi-pri" + ".value " + str(getPendingPriority(200)) )

def doConfig():
    print "graph_title Hive pending priorities"
    print "graph_args --base 1000 -l 0"
    print "graph_vlabel Number"
    print "graph_category mongodb"
    print "graph_total total"

    kname = "Low Priority"
    kval = "low-pri"
    print(kval + ".label " + kname)
    print(kval + ".info " + kname)
    print kval + ".type GAUGE"
    print kval + ".min 0"
    print kval + ".draw AREASTACK"

    kname = "Medium Priority"
    kval = "med-pri"
    print(kval + ".label " + kname)
    print(kval + ".info " + kname)
    print kval + ".type GAUGE"
    print kval + ".min 0"
    print kval + ".draw AREASTACK"

    kname = "High Priority"
    kval = "hi-pri"
    print(kval + ".label " + kname)
    print(kval + ".info " + kname)
    print kval + ".type GAUGE"
    print kval + ".min 0"
    print kval + ".draw AREASTACK"


if __name__ == "__main__":
    from os import environ
    if 'HIVE_DB_URI' in environ:
        uri = environ['HIVE_DB_URI']

    if len(sys.argv) > 1 and sys.argv[1] == "config":
        doConfig()
    else:
        doData()
