#!/usr/bin/env python

import sys
import os
import pymongo
import datetime as dt
import calendar

def getModules():
    if 'HIVE_DB_URI' in os.environ:
        uri = os.environ['HIVE_DB_URI']
    c = pymongo.MongoClient(uri)
    db_name = uri.split('/')[-1].strip()
    proj = {"$project" : {"_id" : 1.0, "description" : "$description", "name" : "$name", "hardware": "$hardware"}}
    return c[db_name].get_collection("hiveavailablemodules").aggregate([proj])

def getFailedJobs(module, ts, now):
    if 'HIVE_DB_URI' in os.environ:
        uri = os.environ['HIVE_DB_URI']
    c = pymongo.MongoClient(uri)
    db_name = uri.split('/')[-1].strip()
    if module == "hive_imagery":
        return 0
    if module == "hive_multireg":
        return c[db_name].get_collection("hivejobs").find({"state_last_updated":{"$gt":ts,"$lte":now},
                                                           "pipeline_name":"waggle_multireg",
                                                           "state":"failed",
                                                           "error_message":{"$ne":"Failed to register with sufficient confidence\n"},
                                                           "current_module_name":"hive.georegistration"}).count()
    if module == "hive_georegistration":
        return c[db_name].get_collection("hivejobs").find({"state_last_updated":{"$gt":ts,"$lte":now},
                                                           "pipeline_name":"waggle",
                                                           "state":"failed",
                                                           "error_message":{"$ne":"Failed to register with sufficient confidence\n"},
                                                           "current_module_name":module.replace("hive_", "hive.")}).count()
    return c[db_name].get_collection("hivejobs").find({"state_last_updated":{"$gt":ts,"$lte":now},
                                                       "state":"failed",
                                                       "current_module_name":module.replace("hive_", "hive.")}).count()

def doData():
    current = dt.datetime.utcnow()
    # current_td = dt.timedelta(hours=current.hour, minutes=current.minute, seconds=current.second, microseconds=current.microsecond)
    # TODO figure out good time stamp 5 minutes ago
    start = current - dt.timedelta(minutes=5)
    ts = calendar.timegm(start.timetuple())
    now = calendar.timegm(current.timetuple())

    jj = {}
    for j in getModules():
        jj[j["_id"]] = getFailedJobs(j["_id"], ts, now)
    for jkey, jval in jj.items():
        print( jkey + ".value " + str(jval) )
    print( "hive_multireg" + ".value " + str(getFailedJobs("hive_multireg", ts, now)) )

def doConfig():
    print "graph_title Cluster failed jobs"
    print "graph_args --base 1000 -l 0"
    print "graph_vlabel Number"
    print "graph_category mongodb"
    print "graph_total total"

    for k in getModules():
        kname = k["_id"]
        print(kname + ".label " + k["name"])
        print(kname + ".info " + k["description"])
        print kname + ".type GAUGE"
        print kname + ".min 0"
        print kname + ".draw AREASTACK"

    kname = "Multi Registration"
    kval = "hive_multireg"
    print(kval + ".label " + kname)
    print(kval + ".info " + kname)
    print kval + ".type GAUGE"
    print kval + ".min 0"
    print kval + ".draw AREASTACK"


if __name__ == "__main__":
    from os import environ
    if 'HIVE_DB_URI' in environ:
        uri = environ['HIVE_DB_URI']

    if len(sys.argv) > 1 and sys.argv[1] == "config":
        doConfig()
    else:
        doData()
